swagger: "2.0"
info:
  version: "0"
  title: WebWallet API
  description: A digital wallet specification for the Web.
host: localhost
basePath: /
schemes:
  - https
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
  
paths:
  /:
    x-swagger-router-controller: endpoints
    get:
      description: Returns a set of instructions for getting started with the API.
      tags: ["basepath"]
      operationId: basepath.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WelcomeBasepath"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /address:
    x-swagger-router-controller: endpoints
    get:
      description: Generates and returns a new wallet address.
      tags: ["address"]
      operationId: wallet.address.new.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NewAddressGET"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      parameters:
      - name: currency
        in: formData
        type: string
      - name: lowerLimit
        in: formData
        type: number
      - name: upperLimit
        in: formData
        type: number
      description: Generates and stores a new wallet address.
      tags: ["address"]
      operationId: wallet.address.new.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NewAddressPOST"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /address/{walletAddress}:
    x-swagger-router-controller: endpoints
    parameters:
      - name: walletAddress
        in: path
        description: A webwallet address
        required: true
        type: string
    get:
      description: Retrieves the representation of an existing wallet address.
      tags: ["address"]
      operationId: wallet.address.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WalletAddressGET"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /address/{walletAddress}/balance:
    x-swagger-router-controller: endpoints
    parameters:
      - name: walletAddress
        in: path
        description: A webwallet address
        required: true
        type: string
    get:
      description: Retrieves the balance of a wallet address.
      tags: ["balance"]
      operationId: wallet.address.balance.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WalletAddressBalanceGET"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 

###-------------------------------------------###
###--------------- DEFINITIONS ---------------###           
definitions:
  WelcomeBasepath:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        $ref: "#/definitions/Properties-Basepath"
      entities:
        $ref: "#/definitions/REST-SubEntities"
      actions:
        $ref: "#/definitions/REST-Actions"
      links:
        $ref: "#/definitions/REST-Links"
# GET /address
  NewAddressGET:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        $ref: "#/definitions/Properties-NewAddressGET"
      entities:
        $ref: "#/definitions/Entities-NewAddressGET"
      actions:
        $ref: "#/definitions/REST-Actions"
      links:
        $ref: "#/definitions/REST-Links"
  NewAddressPOST:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        $ref: "#/definitions/Properties-NewAddressPOST"
      entities:
        $ref: "#/definitions/Entities-NewAddressPOST"
      actions:
        $ref: "#/definitions/REST-Actions"
      links:
        $ref: "#/definitions/REST-Links"
  WalletAddressGET:
    required:
      - type
      - address
    properties:
      type:
        type: string
      address:
        type: string
  WalletAddressBalanceGET:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        $ref: "#/definitions/Properties-WalletAddressBalanceGET"
      entities:
        $ref: "#/definitions/Entities-NewAddressPOST"
      actions:
        $ref: "#/definitions/REST-Actions"
      links:
        $ref: "#/definitions/REST-Links"
  
  CryptoKeyPair:
    required:
      - scheme
      - public
    properties:
      scheme:
        $ref: "#/definitions/EncryptionScheme"
      public: 
        $ref: "#/definitions/PublicCryptoKey"
      private: 
        $ref: "#/definitions/PrivateCryptoKey"
  EncryptionScheme:
    type: string
    description: The code name of an encryption scheme.
    example: secp256k1
  PublicCryptoKey:
    type: string
    format: hex
    description: A public cryptographic key in hexadecimal format.
  PrivateCryptoKey:
    type: string
    format: hex
    description: A private cryptographic key in hexadecimal format.
  
###----- BODY SCHEMAS -----###
  NewAddressPOST-Body:
    type: object
    properties:
      currency:
        type: string
###----- PROPERTIES ATTRIBUTES FOR EACH ENDPOINT -----###  
  Properties-Basepath:
    type: object
    description: The properties of the basepath document
    required:
      - name
      - version
      - description
    properties:
      name:
        type: string
        description: The name of the API.
      version:
        $ref: "#/definitions/api-version"
      description:
        $ref: "#/definitions/description"
      tips:
        type: array
        description: Tips for getting started with the API.
        items:
          type: string
  Properties-NewAddressGET:
    type: object
    description: The properties of the new wallet address.
    required:
      - address
      - type
    properties:
      address:
        $ref: "#/definitions/WalletAddress"
      type:
        type: string
        description: The type of address.
  Properties-NewAddressPOST:
    type: object
    description: The properties of the new wallet address.
    required:
      - address
      - type
    properties:
      address:
        $ref: "#/definitions/WalletAddress"
      type:
        type: string
        description: The type of address.
  Properties-WalletAddressBalanceGET:
    type: object
    description: The balance of a wallet address.
    required:
      - address
      - balance
      - currency
    properties:
      address:
        $ref: "#/definitions/WalletAddress"
      balance:
        type: number
      currency:
        $ref: "#/definitions/Currency"

###----- ENTITIES ATTRIBUTES FOR EACH ENDPOINT -----###         
  Entities-NewAddressGET:
    type: array
    description: A collection of sub-entities of a wallet address.
    items:
      $ref: "#/definitions/Entity-NewAddressGET"
  Entity-NewAddressGET:
    type: object
    description: Sub-entities of a wallet address.
    required:
      - keys
    properties:
      keys:
        $ref: "#/definitions/CryptoKeyPair"
  Entities-NewAddressPOST:
    type: array
    description: A collection of sub-entities of a wallet address.
    items:
      $ref: "#/definitions/Entity-NewAddressPOST"
  Entity-NewAddressPOST:
    type: object
    description: Sub-entities of a wallet address.
    required:
      - keys
    properties:
      keys:
        $ref: "#/definitions/CryptoKeyPair"
    
###----- REST API RESPONSE COMPONENTS -----###

# "links" attribute      
  REST-Links:
    type: array
    description: A collection of navigational links.
    items:
      $ref: "#/definitions/REST-Link"
# "links" element
  REST-Link:
    type: object
    description: Represents a navigational transition to a related resource.
    required:
      - rel
      - href
    properties:
      rel:
        $ref: "#/definitions/rel"
      href:
        $ref: "#/definitions/href"
      
# "entities" attribute
  REST-SubEntities:
    type: array
    description: A collection of sub-entities.
    items:
      $ref: "#/definitions/REST-SubEntity"
# "entities" element
  REST-SubEntity:
    type: object
    description: An embedded link or representation of a resource that has properties, actions and other resources associated with it.
    required:
      - rel
      - href
    properties:
      rel:
        $ref: "#/definitions/rel"
      href:
        $ref: "#/definitions/href"
        
# "actions" attribute
  REST-Actions:
    type: array
    description: A collection of behaviors exposed by the resource.
    items:
      $ref: "#/definitions/REST-Action"
# "actions" element
  REST-Action:
    type: object
    description: Represents a behaviour exposed by the resource.
    required:
      - name
      - href
      - method
    properties:
      name:
        $ref: "#/definitions/name"
      href:
        $ref: "#/definitions/href"
      method:
        $ref: "#/definitions/method"
      fields:
        $ref: "#/definitions/fields"

# "rel" and "href" attributes
  rel:
    type: string
    description: Describes the relationship between the link and the entity listing it.
    example: self,parent,previous,next
  href:
    type: string
    description: The URI of the resource, collection or action.
    example: https://example.com/path/to/a/resource
    
# "method" attribute
  method:
    type: string
    description: An HTTP method.
    example: GET,POST,PUT,DELETE
# "name" attribute
  name:
    type: string
    description: The name of the resource, collection or action.
# "description" attribute
  description:
    type: string
    description: The description of the resource, collection or action.
# "api-version" attribute
  api-version:
    type: string
    description: The version of the queried API.
# "fields" attribute
  fields:
    type: array
    description: A collection of request fields.
    items:
      $ref: "#/definitions/field"
  field:
    type: object
    description: A request field.
    required:
      - name
    properties:
      name:
        type: string
        description: The name of the field.
      type:
        type: string
        description: The data type of the field.
      value:
        description: The default value of the field.
# "address" attribute
  WalletAddress:
    type: string
    format: base58
    description: The hash of a public key in base58check encoding.
    example: wcvKsFjqCEutppnik5xV9PhvsN4n2FEunE
  Currency:
    type: string
    description: A currency code optionally followed by a circle identifier (separeted by a colon)
    example: IOU[:ABCDEFG]
    
###---------- ERROR RESPONSES ----------###
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
