swagger: "2.0"
info:
  version: "0.0.1"
  title: WebWallet API
  description: A digital wallet specification for the Web.
host: localhost
basePath: /
schemes:
  - https
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
  
paths:
  /:
    x-swagger-router-controller: endpoints
    get:
      description: Returns a set of instructions for getting started with the API.
      tags: ["basepath"]
      operationId: basepath.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WelcomeBasepath"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /address:
    x-swagger-router-controller: endpoints
    get:
      description: Generates and returns a new wallet address.
      tags: ["address"]
      operationId: wallet.address.new.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NewAddressGET"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Generates and stores a new wallet address.
      tags: ["address"]
      operationId: wallet.address.new.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NewAddressPOST"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /address/{walletAddress}:
    x-swagger-router-controller: endpoints
    parameters:
      - name: walletAddress
        in: path
        description: A webwallet address
        required: true
        type: string
    get:
      description: Retrieves the representation of an existing wallet address.
      tags: ["address"]
      operationId: wallet.address.get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WalletAddressGET"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 

###-------------------------------------------###
###--------------- DEFINITIONS ---------------###           
definitions:
  WelcomeBasepath:
    required:
      - properties
      - links
      - entities
      - actions
    properties:
      properties:
        $ref: "#/definitions/REST-Properties-Basepath"
      links:
        $ref: "#/definitions/REST-Links"
      entities:
        $ref: "#/definitions/REST-SubEntities"
      actions:
        $ref: "#/definitions/REST-Actions"
  NewAddressGET:
    required:
      - address
      - keys
    properties:
      address: 
        $ref: "#/definitions/WalletAddress"
      keys:
        $ref: "#/definitions/CryptoKeyPair"
  NewAddressPOST:
    required:
      - address
      - keys
    properties:
      address:
        $ref: "#/definitions/WalletAddress"
      keys:
        $ref: "#/definitions/CryptoKeyPair"
  WalletAddressGET:
    required:
      - type
      - address
    properties:
      type:
        type: string
      address:
        type: string
  
  CryptoKeyPair:
    required:
      - scheme
      - public
      - private
    properties:
      scheme:
        $ref: "#/definitions/EncryptionScheme"
      public: 
        $ref: "#/definitions/PublicCryptoKey"
      private: 
        $ref: "#/definitions/PrivateCryptoKey"
  EncryptionScheme:
    type: string
    description: The code name of an encryption scheme.
    example: secp256k1
  PublicCryptoKey:
    type: string
    format: hex
    description: A public cryptographic key in hexadecimal format.
  PrivateCryptoKey:
    type: string
    format: hex
    description: A private cryptographic key in hexadecimal format.
  WalletAddress:
    type: string
    format: base58
    description: The hash of a public key in base58check encoding.
    example: wcvKsFjqCEutppnik5xV9PhvsN4n2FEunE

###----- PROPERTIES ATTRIBUTES FOR EACH ENDPOINT -----###  
  REST-Properties-Basepath:
    type: object
###----- REST API RESPONSE COMPONENTS -----###

# "links" attribute      
  REST-Links:
    type: array
    description: A collection of navigational links
    items:
      $ref: "#/definitions/REST-Link"
# "links" element
  REST-Link:
    type: object
    description: Represents a navigational transition to a related entity.
    required:
      - rel
      - href
    properties:
      rel:
        $ref: "#/definitions/REST-Rel"
      href:
        $ref: "#/definitions/REST-Href"
      
# "entities" attribute
  REST-SubEntities:
    type: array
    description: A collection of sub-entities
    items:
      $ref: "#/definitions/REST-SubEntity"
# "entities" element
  REST-SubEntity:
    type: object
    description: An embedded link or representation of a resource that has properties, actions and other resources associated with it.
    required:
      - rel
      - href
    properties:
      rel:
        $ref: "#/definitions/REST-Rel"
      href:
        $ref: "#/definitions/REST-Href"
        

# "actions" attribute
  REST-Actions:
    type: array
    description: A collection of behaviors exposed by an entity
    items:
      $ref: "#/definitions/REST-Action"
# "actions" element
  REST-Action:
    type: object
    description: Represents a behaviour exposed by an entity
    required:
      - name
      - href
      - method
    properties:
      name:
        $ref: "#/definitions/REST-Name"
      href:
        $ref: "#/definitions/REST-Href"
      method:
        $ref: "#/definitions/REST-Method"

# "rel" and "href" attributes
  REST-Rel:
    type: string
    description: Describes a relationship between a link and the entity listing it.
    example: self,parent,previous,next
  REST-Href:
    type: string
    description: The URI of a resource.
    example: https://example.com/path/to/a/resource
    
# "method" attribute
  REST-Method:
    type: string
    description: An HTTP method.
    example: GET,POST,PUT,DELETE
# "name" attribute
  REST-Name:
    type: string
    description: The name of a resource.
    
###---------- ERROR RESPONSES ----------###
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
